[package]
name = "iyes_progress"
version = "0.11.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/IyesGames/iyes_progress"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy_ecs = { version = "0.13.2" }
bevy_app = { version = "0.13.2" }
bevy_asset = { version = "0.13.2", optional = true }
bevy_log = { version = "0.13.2", optional = true }
bevy_utils = { version = "0.13.2" }

[features]
# Support for simple tracking of asset loading
assets = ["bevy_asset"]
# Support for debug functionality (such as logging progress to console)
debug = ["bevy_log"]

[dev-dependencies]
bevy = { version = "0.13.2" }

[[example]]
name = "full"
required-features = ["assets"]
