[package]
name = "iyes_progress"
version = "0.8.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/IyesGames/iyes_progress"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }

[features]
assets = ["bevy/bevy_asset"]

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy" }

[[example]]
name = "full"
required-features = ["assets"]
