[package]
name = "iyes_progress"
version = "0.8.0"
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/IyesGames/iyes_progress"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy_ecs = { version = "0.10" }
bevy_app = { version = "0.10" }
bevy_asset = { version = "0.10", optional = true }
bevy_utils = { version = "0.10", optional = true }

[features]
assets = ["bevy_asset", "bevy_utils"]

[dev-dependencies]
bevy = { version = "0.10" }

[[example]]
name = "full"
required-features = ["assets"]
