[package]
name = "bevy_loading"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/inodentry/bevy_loading"
keywords = ["game", "gamedev", "bevy"]
categories = ["game-engines"]
description = "Bevy plugin to help implement loading states"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git", default-features = false }

[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy.git" }
